### ISSUE TITLE
legs.py  not working in python3

### ISSUE THREAD

**Issue by RogueM** [pimoroni/piglow#4]
pi@raspberrypi:~/Pimoroni/piglow$ python3 legs.py 
Traceback (most recent call last):
  File "legs.py", line 13, in <module>
    piglow.set(0, map(lambda x: x - 1 if x > 1 else 0, piglow.get()))
  File "/usr/local/lib/python3.4/dist-packages/piglow.py", line 81, in set
    _set(leds, value)
  File "/usr/local/lib/python3.4/dist-packages/piglow.py", line 110, in _set
    _values[leds] = (value % 256)
TypeError: unsupported operand type(s) for %: 'map' and 'int'

**Comment by Gadgetoid** [comment]
Should be fixed in: 06e86c974536c354ccaa2a127f16240eff434db1
